"""Shared pytest fixtures for pipeline tests."""

from __future__ import annotations

import json
from pathlib import Path

import pytest


# Path to pipeline output (generated by running the full pipeline)
OUTPUT_DIR = Path(__file__).parent.parent / "output"


@pytest.fixture
def output_dir() -> Path:
    """Path to pipeline output directory. Skip tests if it doesn't exist."""
    if not OUTPUT_DIR.exists():
        pytest.skip("Pipeline output not generated yet -- run the pipeline first")
    return OUTPUT_DIR


@pytest.fixture
def competitions_json(output_dir: Path) -> dict:
    path = output_dir / "competitions.json"
    if not path.exists():
        pytest.skip("competitions.json not found")
    with open(path) as f:
        return json.load(f)


@pytest.fixture
def keepers_json_2018(output_dir: Path) -> dict:
    """keepers.json for the 2018 World Cup (competition_id=43, season_id=3)."""
    path = output_dir / "43_3" / "keepers.json"
    if not path.exists():
        pytest.skip("2018 WC keepers.json not found")
    with open(path) as f:
        return json.load(f)
